INSERT INTO Place (`id`, `city`, `country`, `month`) 
VALUES 
(1, 'Zadar', 'Croatia', 'September'),
(2, 'Oslo', 'Norway', 'September'),
(3, 'Geneve', 'Switzerland', 'September'),
(4, 'Antwerp', 'Belgium', 'October'),
(5, 'Agadir', 'Morocco', 'October'),
(6, 'Nantes', 'France', 'October'),
(7, 'Helsinki', 'Finland', 'November'),
(8, 'Ede', 'Netherlands', 'November'),
(9, 'Dublin', 'Ireland', 'November'),
(10, 'Rome', 'Italy', 'November'),
(11, 'Darmstadt', 'Germany', 'November'),
(12, 'Tokyo', 'Japan', 'December'),
(13, 'Singapore', 'Singapore', 'December'),
(14, 'Stockholm', 'Sweden', 'February'),
(15, 'Amsterdam', 'Netherlands', 'February'),
(16, 'Los Angeles', 'USA', 'March'),
(17, 'Paris', 'France', 'March'),
(18, 'Atlanta', 'USA', 'April'),
(19, 'Bangalore', 'India', 'April');